go run VMTranslator.go examples/FunctionCalls/FibonacciElement
go run VMTranslator.go examples/FunctionCalls/NestedCall/
go run VMTranslator.go examples/FunctionCalls/SimpleFunction
go run VMTranslator.go examples/FunctionCalls/StaticsTest/
go run VMTranslator.go examples/MemoryAccess/BasicTest/BasicTest.vm
go run VMTranslator.go examples/MemoryAccess/PointerTest
go run VMTranslator.go examples/MemoryAccess/StaticTest/
go run VMTranslator.go examples/ProgramFlow/BasicLoop/BasicLoop.vm
go run VMTranslator.go examples/ProgramFlow/FibonacciSeries
go run VMTranslator.go examples/StackArithmetic/SimpleAdd
go run VMTranslator.go examples/StackArithmetic/SimpleAnd/
go run VMTranslator.go examples/StackArithmetic/SimpleEqFalse
go run VMTranslator.go examples/StackArithmetic/SimpleEqTrue/
go run VMTranslator.go examples/StackArithmetic/SimpleNeg/SimpleNeg.vm
go run VMTranslator.go examples/StackArithmetic/SimpleNot/SimpleNot.vm
go run VMTranslator.go examples/StackArithmetic/SimpleOr
go run VMTranslator.go examples/StackArithmetic/SimpleSub/
go run VMTranslator.go examples/StackArithmetic/StackTest/StackTest.vm

